In [ ]:
%load_ext autoreload
%autoreload 2
from tools import EnergyStorageModel

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
import numpy as np

In [40]:
# Example Usage:
model = EnergyStorageModel(price_data_path='../data/entsoe_price_DK_1_20150101_20240101.csv')
model.compute_price_transitions()
V, P = model.value_function_iteration()

Converged in 1389 iterations.


In [48]:
V2, P2 = model.vfi_vec()

Converged in 146 iterations.


In [49]:
np.allclose(P, P2)
print(P)
print(P2)

[[ 7.2  7.2  7.2  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 7.2  7.2  7.2  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 3.6  3.6  3.6  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 3.6  3.6  3.6  3.6  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 3.6  3.6  3.6  0.   0.  -3.6 -3.6 -3.6 -3.6 -3.6 -3.6 -3.6]
 [ 3.6  3.6  3.6  0.   0.  -3.6 -3.6 -3.6 -3.6 -3.6 -3.6 -3.6]
 [ 0.   0.   0.   0.   0.  -3.6 -3.6 -3.6 -3.6 -3.6 -3.6 -3.6]
 [ 0.   0.   0.   0.   0.  -3.6 -3.6 -3.6 -3.6 -3.6 -3.6 -3.6]
 [ 0.   0.   0.   0.   0.  -7.2 -7.2 -7.2 -7.2 -7.2 -7.2 -7.2]
 [ 0.   0.   0.   0.   0.  -7.2 -7.2 -7.2 -7.2 -7.2 -7.2 -7.2]]
[[4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]
 [4 4 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
battery_storage_sim, profit_sim = model.simulate()
model.plot_results(battery_storage_sim, profit_sim)
